gym:
    resource: "@GymBundle/Resources/config/routing.yml"
    prefix:   /

boxer:
    resource: "@BoxerBundle/Resources/config/routing.yml"
    prefix:   /

# app:
#     resource: '@AppBundle/Controller/'
#     type: annotation
