boxer_homepage:
    path:     /
    defaults: { _controller: BoxerBundle:Boxer:index }

boxer_profile:
    path:     /boxer/register
    defaults: { _controller: BoxerBundle:Boxer:newBoxer }
    methods: [GET]

api_boxer_new:
    path:     /boxer/create
    defaults: { _controller: BoxerBundle:Boxer:createBoxer }
    methods: [POST]
