boxer_homepage:
    path:     /
    defaults: { _controller: BoxerBundle:Boxer:index }

boxer_register:
    path:     /boxer/register
    defaults: { _controller: BoxerBundle:Boxer:newBoxer }
    methods: [GET]

boxer_register_check:
    path:     /boxer/register_check
    defaults: { _controller: BoxerBundle:Form:validNewBoxer }
    methods: [POST]

boxer_new:
    path:     /boxer/create
    defaults: { _controller: BoxerBundle:Boxer:createBoxer }
    methods: [POST]

boxer_show:
    path:     /boxer/show/{id}
    defaults: { _controller: BoxerBundle:Boxer:showBoxer }
    methods: [GET]
    
boxer_delete:
    path:     /boxer/delete/{id}
    defaults: { _controller: BoxerBundle:Boxer:deleteBoxer }
    methods: [GET]

boxer_update:
    path:     /boxer/update/{id}
    defaults: { _controller: BoxerBundle:Boxer:updateBoxer }
    methods: [POST]

boxer_send_email:
    path:     /boxer/send/{id}
    defaults: { _controller: BoxerBundle:Boxer:sendToBoxer }
    methods: [POST]