gym_homepage:
    path:     /
    defaults: { _controller: BoxerBundle:Boxer:index }
    
gym_register:
    path:     /gyms/register
    defaults: { _controller: GymBundle:Gym:newGym }
    methods: [GET]

gym_new:
    path:     /gyms/create
    defaults: { _controller: GymBundle:Gym:createGym }
    methods: [POST]

gym_show:
    path:     /gyms/show/{id}
    defaults: { _controller: GymBundle:Gym:showGym }
    methods: [GET]
    
gym_delete:
    path:     /gyms/delete/{id}
    defaults: { _controller: GymBundle:Gym:deleteGym }
    methods: [GET]

gym_update:
    path:     /gyms/update/{id}
    defaults: { _controller: GymBundle:Gym:updateGym }
    methods: [POST]