gym_homepage:
    path:     /
    defaults: { _controller: BoxerBundle:Boxer:index }
    
gym_register:
    path:     /gyms/register
    defaults: { _controller: GymBundle:Gym:newGym }
    methods: [GET]

api_gym_new:
    path:     /gyms/create
    defaults: { _controller: GymBundle:Gym:createGym }
    methods: [POST]